# Generated by Django 6.0 on 2026-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Аватар",
                null=True,
                upload_to="avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
