# Generated by Django 6.0 on 2026-01-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adv", "0004_alter_review_author_review_unique_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="adv.advertisement",
                verbose_name="Объявление",
            ),
        ),
    ]
